name: folly_fields_example
description: A new Flutter project.

publish_to: 'none'

version: 0.2.21+66

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/edufolly/folly_fields
  folly_fields:
    path: ../

  # https://pub.dev/packages/http
  http: 0.13.3
  # https://pub.dev/packages/url_launcher
  url_launcher: 6.0.10
  # https://pub.dev/packages/google_fonts
  google_fonts: 2.1.0
  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: 0.7.0
  # https://pub.dev/packages/connectivity
  connectivity: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
