name: rfid_fields
description: Basic form fields and utilities.
version: 0.2.21+66
# author:
homepage: https://github.com/RFIDBrasil-TI/rfid-fields

# TODO - Remove
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^9.0.0
  # https://pub.dev/packages/connectivity
  connectivity: ^3.0.3
  # https://pub.dev/packages/email_validator
  email_validator: ^2.0.1
  # https://pub.dev/packages/cpf_cnpj_validator
  cpf_cnpj_validator: ^2.0.0
  # https://pub.dev/packages/sprintf
  sprintf: ^6.0.0
  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
